### ISSUE TITLE
output just a dependency tree?

### ISSUE THREAD

**Issue by adhamhf** [stefanpenner/broccoli-viz#30]
Is it possible to just output a dependency tree?  I'm unsure if that would be in scope for this module.  I'd be happy to take a stab at implementing.

**Comment by stefanpenner** [comment]
this actually consumes the dependency tree outputed by ember-cli.

**Comment by adhamhf** [comment]
Oh.  Is it possible to graph that?

I'm unsure of what this tool's use case is.

**Comment by stefanpenner** [comment]
yes, its an encoded graph.

**Comment by hjdivad** [comment]
@adhamhf check out https://github.com/ember-cli/ember-cli/blob/master/PERF_GUIDE.md#broccoli-viz and https://github.com/ember-cli/broccoli-viz#usage for usage.

The tl;dr is
1. generate the build tree json
2. use `broccoli-viz` to produce a dotfile of this tree.
3. use `graphviz` to produce something viewable (svg, pdf, png &c.) from that dotfile.

**Comment by adhamhf** [comment]
Thanks @hjdivad.  I'm looking for something more like https://github.com/wyvernnot/npm2dot.  Its just the npm dependency graph....
